FROM python:3.9-slim

WORKDIR /app

# Install Java for Spark
RUN apt-get update && apt-get install -y default-jre && apt-get clean

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "spark_consumer.py"]
