services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.21
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch

  batch_scraper:
    build:
      context: .
      dockerfile: Dockerfile.batch_scraper
    depends_on:
      - elasticsearch
    environment:
      - ES_HOST=http://elasticsearch:9200
    volumes:
      - ./models:/app/models

  batch_trainer:
    build:
      context: .
      dockerfile: Dockerfile.batch_trainer
    depends_on:
      - elasticsearch
    environment:
      - ES_HOST=http://elasticsearch:9200
    volumes:
      - ./models:/app/models

  live_scraper:
    build:
      context: .
      dockerfile: Dockerfile.live_scraper
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    volumes:
      - ./models:/app/models

  live_predict:
    build:
      context: .
      dockerfile: Dockerfile.live_predict
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - ES_HOST=http://elasticsearch:9200
    depends_on:
      - kafka
      - elasticsearch
    volumes:
      - ./models:/app/models

volumes:
  esdata:
